services:
  vehicleregistrationdb:
    image: postgres:16
    container_name: vehicleregistrationdb
    environment:
      - POSTGRES_DB=VehicleRegistrationDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Frankenstein@123
    ports:
      - "5433:5432"
    volumes:
      - vehicleregdbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  insurancedb:
    image: postgres:16
    container_name: insurancedb
    environment:
      - POSTGRES_DB=InsuranceDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Frankenstein@123
    ports:
      - "5434:5432"
    volumes:
      - insurancedbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  vehicleregistrationapi:
    build:
      context: .
      dockerfile: VehicleRegistrationAPI/Dockerfile
    container_name: vehicleregistrationapi
    ports:
      - "5059:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=vehicleregistrationdb;Port=5432;Database=VehicleRegistrationDB;Username=postgres;Password=Frankenstein@123
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      vehicleregistrationdb:
        condition: service_healthy
      redis:
        condition: service_healthy

  insuranceapi:
    build:
      context: .
      dockerfile: InsuranceAPI/Dockerfile
    container_name: insuranceapi
    ports:
      - "5096:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=insurancedb;Port=5432;Database=InsuranceDB;Username=postgres;Password=Frankenstein@123
      - ConnectionStrings__Redis=redis:6379
      - VehicleRegistrationAPIUrl=http://vehicleregistrationapi:80
    depends_on:
      insurancedb:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  vehicleregdbdata:
  insurancedbdata:
  redisdata: